services:
  postgres:
    image: 'postgres:16-alpine' #  una versi√≥n especifica y ligera
    restart: unless-stopped
    environment:
      - POSTGRES_DB=music_play
      - POSTGRES_USER=music909
      - POSTGRES_PASSWORD=musicplay303
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: